/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageRouteRouteImport } from './routes/page/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageSampleGridIndexRouteImport } from './routes/page/sample/grid/index'
import { Route as PageSampleFormIndexRouteImport } from './routes/page/sample/form/index'

const PageRouteRoute = PageRouteRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSampleGridIndexRoute = PageSampleGridIndexRouteImport.update({
  id: '/sample/grid/',
  path: '/sample/grid/',
  getParentRoute: () => PageRouteRoute,
} as any)
const PageSampleFormIndexRoute = PageSampleFormIndexRouteImport.update({
  id: '/sample/form/',
  path: '/sample/form/',
  getParentRoute: () => PageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/page/sample/form': typeof PageSampleFormIndexRoute
  '/page/sample/grid': typeof PageSampleGridIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/page/sample/form': typeof PageSampleFormIndexRoute
  '/page/sample/grid': typeof PageSampleGridIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page': typeof PageRouteRouteWithChildren
  '/page/sample/form/': typeof PageSampleFormIndexRoute
  '/page/sample/grid/': typeof PageSampleGridIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page' | '/page/sample/form' | '/page/sample/grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page' | '/page/sample/form' | '/page/sample/grid'
  id: '__root__' | '/' | '/page' | '/page/sample/form/' | '/page/sample/grid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRouteRoute: typeof PageRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/sample/grid/': {
      id: '/page/sample/grid/'
      path: '/sample/grid'
      fullPath: '/page/sample/grid'
      preLoaderRoute: typeof PageSampleGridIndexRouteImport
      parentRoute: typeof PageRouteRoute
    }
    '/page/sample/form/': {
      id: '/page/sample/form/'
      path: '/sample/form'
      fullPath: '/page/sample/form'
      preLoaderRoute: typeof PageSampleFormIndexRouteImport
      parentRoute: typeof PageRouteRoute
    }
  }
}

interface PageRouteRouteChildren {
  PageSampleFormIndexRoute: typeof PageSampleFormIndexRoute
  PageSampleGridIndexRoute: typeof PageSampleGridIndexRoute
}

const PageRouteRouteChildren: PageRouteRouteChildren = {
  PageSampleFormIndexRoute: PageSampleFormIndexRoute,
  PageSampleGridIndexRoute: PageSampleGridIndexRoute,
}

const PageRouteRouteWithChildren = PageRouteRoute._addFileChildren(
  PageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRouteRoute: PageRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
